### ISSUE TITLE
Step: 003 - Ingress for Hetzner with Loadbalancer (Ingress kann nicht gestartet werden)

### ISSUE THREAD

**Issue by OV2012** [srcmkr/csharpdevops#1]
hi,
vorab: ihre Anleitung  finde ich einfach super! richtig richtig hilfreich!
bin allerdings aktuell bei dem Step 3 stecken geblieben! :)
das Problem: der ingress-controller läuft zwar (state=running) aber sein log ist voll mit den nachfolgenden errors
haben Sie vielleicht eine Idee, woran es liegen kann?

_Finalizers:[],ClusterName:,Initializers:nil,}, err services "ingress-controller" not found
W0629 06:40:42.329850       7 queue.go:130] requeuing &ObjectMeta{Name:sync status,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]_

Gruß
Viktor

**Comment by srcmkr** [comment]
Moin Viktor,
wenn du 001 (manuell) oder 002 ("automatisch") zum Aufsetzen des Clusters genommen hast, sollte er eigentlich alles haben um den Ingress zu finden.

Was für eine Ausgabe kommt, wenn du ``kubectl get ingress`` eingibst?

**Comment by OV2012** [comment]
Hi Ben, 
sorry für die verzögerte Reaktion .
ich hab irgendwie deine Nachricht verpasst.
also ich hab noch mal alles komplett from scratch aufgesetzt und jetzt ist alles grün!
super!
jetzt versuche ich mit deiner Terraform-Anleitung weiter  :)
und noch mal vielen Dank für die tolle Videos und den Support!
ich denke wir können dieses Issue nun schließen
schönes WE
Gruß
Viktor
